spring:
  application:
    name: maps-be-v1
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          semaphore:
            maxConcurrentRequests: 100000 # basically 'unlimited'
        timeout:
          enabled: false
        circuitBreaker:
          enabled: false
        fallback:
          enabled: false
ribbon:
  ReadTimeout: 600000
  ConnectTimeout: 600000
feign:
  client:
    config:
      default:
        connectTimeout: 600000
        readTimeout: 600000