spring:
  application:
    name: maps-be-v1
server:
  port: 8080
NUMBER_OF_POINTS_TO_GENERATE: 30
NUMBER_OF_ITERATIONS: 3
NUMBER_OF_BEST_POINTS_FILTER: 15
VALHALLA_SERVICE_URL: https://valhalla-45iud4jnfq-uc.a.run.app